#include <iostream>

int main() {
    std::string html = R"(
    <!DOCTYPE html>
    <html>
    <head>
        <title>My Web Page</title>
    </head>
    <body>
        <h1>Hello, World!</h1>
        <p>This is a simple HTML page generated by a C++ program.</p>
    </body>
    </html>
    )";

    std::cout << "Content-Type: text/html\n\n";
    std::cout << html;

    return 0;
}
